apiVersion: apps/v1
kind: Deployment
metadata:
  name: sukhodolsky-nginx   
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sukhodolsky-app    
  template:
    metadata:
      labels:
        app: sukhodolsky-app  
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
